### ISSUE TITLE
Trying to turn on a led without using ble

### ISSUE THREAD

**Issue by onesimo93** [joric/cc2540kbd#2]
I want to use the cc2540 but I don't know how to write code for this as the OSAL layers make it way more difficult than anything I have tried before.

Can you help me?

**Comment by joric** [comment]
Haven't tried honestly. Probably BLE-CC254x-1.4.2.2\Projects\ble helps, all the HalLedSet stuff.
```cpp
// makes sure LEDs are off
HalLedSet( (HAL_LED_1 | HAL_LED_2), HAL_LED_MODE_OFF );
for (i=0; i<12000; i++) asm("NOP"); //1.5ms delay
```
To change LED's change the following in `hal_board_cfg.h`:
```cpp
#define LED1_BV BV(4)
#define LED1_SBIT P1_4
```
